version: '3'
services:
  auth:
    build:
      context: ./backend/api/auth
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - mynetwork

  company:
    build:
      context: ./backend/api/company
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    networks:
      - mynetwork

  schedule:
    build:
      context: ./backend/api/schedule
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - mynetwork

  schedule-confirmation:
    build:
      context: ./backend/api/schedule-confirmation
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: