version: '3'
services:
  auth:
    build:
      context: ./backend/api/auth
    ports:
      - "3001:3001"
    depends_on:
      - db-atecnologia
  company:
    build:
      context: ./backend/api/company
    ports:
      - "3002:3002"
    depends_on:
      - db-atecnologia
  schedule:
    build:
      context: ./backend/api/schedule
    ports:
      - "3003:3003"
    depends_on:
      - db-atecnologia
  db-atecnologia:
    image: postgres:latest
    environment:
      POSTGRES_DB: atecnologia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    entrypoint: ["docker-entrypoint.sh", "postgres"]